### ISSUE TITLE
Not able to import from repository

### ISSUE THREAD

**Issue by Abu-Abdullah** [Clarifai/clarifai-java-grpc#5]
Hi,

not able to import from repository:
Cannot resolve com.google.guava:guava:2j.0-jre

**Comment by rok-clarifai** [comment]
Hi @Abu-Abdullah, we've tested using the library via Maven and were able to replicate the issue. A fix has been released, please upgrade to the (currently) latest version 6.7.1.

Thanks for reporting the issue!
