### ISSUE TITLE
Getting problem in giving the image as ByteString to the api.

### ISSUE THREAD

**Issue by ayushman999** [Clarifai/clarifai-java-grpc#6]
I converted my Clicked picture from Bitmap to ByteArray, which while giving in the API I converted into Byte String but it's not working for me.
This is my code for it.
![image](https://user-images.githubusercontent.com/55322319/98699626-5b16f180-239d-11eb-8bf9-d78dfc769ec8.png)
While this is the error I am getting.
![image](https://user-images.githubusercontent.com/55322319/98699774-7bdf4700-239d-11eb-90fe-cbd8a2034f6b.png)

**Comment by ayushman999** [comment]
Another thing I should specify is that the overall logic of this app works completely fine and I get the result too when I change the input parameter of the image to be a URL and not a ByteArray.

**Comment by aleksander-clarifai** [comment]
Hello @ayushman999
Added integration test to validate the issue. 
https://github.com/Clarifai/clarifai-java-grpc/pull/9/files
Can it be that you are passing an empty byte array to setBase64()?

Best regards,
Aleksander
