### ISSUE TITLE
JCenter is shutting down soon

### ISSUE THREAD

**Issue by umran-canva** [Clarifai/clarifai-java-grpc#8]
Hi,

We're looking to migrate our clarifai Java client to the new gRPC client. However, we found out that JCenter (which the gRPC library depends on) is shutting down soon: [see here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

Are there any plans to move away from JCenter?

**Comment by aleksander-clarifai** [comment]
Hello @umran-canva,

Yes, we are planning to move away from JCenter.

Best regards,
Aleksander B.
